apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: multi-k8s-kharms-co-uk-tls
spec:
  secretName: multi-k8s-kharms-co-uk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s.kharms.co.uk
  dnsNames:
    - multi-k8s.kharms.co.uk